import { useEffect, useState } from 'react';
import { customFetch } from '@workspace/api-client-react';
import AdminLayout from '@/components/AdminLayout';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Checkbox } from '@/components/ui/checkbox';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { useAdminI18n } from '@/contexts/AdminI18nContext';
import { toast } from 'sonner';

type Method = { method:string; isEnabled:boolean; recipientDisplayName:string; recipientAccount:string; instructionsAr:string; instructionsFr:string; minimumAmountMru:number|null; maximumAmountMru:number|null; evidenceRequired:boolean; transactionReferenceRequired:boolean; displayOrder:number };
const empty=(method:string,index:number):Method=>({method,isEnabled:false,recipientDisplayName:'',recipientAccount:'',instructionsAr:'',instructionsFr:'',minimumAmountMru:null,maximumAmountMru:null,evidenceRequired:true,transactionReferenceRequired:false,displayOrder:index});

export default function AdminPaymentMethods(){
 const {lang,isRTL}=useAdminI18n(); const [methods,setMethods]=useState<Method[]>(['bankily','masrvi','sedad'].map(empty)); const [saving,setSaving]=useState<string|null>(null);
 useEffect(()=>{customFetch<{data:Method[]}>('/api/admin/manual-payment-methods',{responseType:'json'}).then(r=>setMethods(['bankily','masrvi','sedad'].map((name,i)=>r.data.find(x=>x.method===name)||empty(name,i)))).catch(()=>toast.error(lang==='ar'?'تعذر تحميل طرق الدفع':'Chargement impossible'))},[]);
 const update=(name:string,patch:Partial<Method>)=>setMethods(v=>v.map(m=>m.method===name?{...m,...patch}:m));
 const save=async(m:Method)=>{setSaving(m.method);try{await customFetch(`/api/admin/manual-payment-methods/${m.method}`,{method:'PATCH',body:JSON.stringify(m),responseType:'json'});toast.success(lang==='ar'?'تم حفظ الإعداد وتدقيقه':'Configuration enregistrée et auditée')}catch{toast.error(lang==='ar'?'تعذر الحفظ':'Enregistrement impossible')}finally{setSaving(null)}};
 return <AdminLayout><div className="mx-auto max-w-5xl space-y-6 p-6" dir={isRTL?'rtl':'ltr'}><div><h1 className="text-3xl font-bold">{lang==='ar'?'طرق الدفع الموريتانية':'Méthodes de paiement mauritaniennes'}</h1><p className="mt-1 text-sm text-muted-foreground">{lang==='ar'?'هذه البيانات تأتي منها تعليمات الهاتف؛ لا تُضمّن حسابات التاجر في التطبيق.':"Ces données alimentent les instructions mobiles; aucun compte marchand n’est codé dans l’application."}</p></div>
 <div className="space-y-4">{methods.map(m=><Card key={m.method} className="p-6"><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-semibold capitalize">{m.method}</h2><label className="flex items-center gap-2 text-sm"><Checkbox checked={m.isEnabled} onCheckedChange={v=>update(m.method,{isEnabled:v===true})}/>{lang==='ar'?'مفعّلة':'Activée'}</label></div><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">{lang==='ar'?'اسم المستلم':'Nom du destinataire'}<Input value={m.recipientDisplayName} onChange={e=>update(m.method,{recipientDisplayName:e.target.value})}/></label><label className="text-sm">{lang==='ar'?'الهاتف/الحساب':'Téléphone / compte'}<Input value={m.recipientAccount} onChange={e=>update(m.method,{recipientAccount:e.target.value})}/></label><label className="text-sm">{lang==='ar'?'الحد الأدنى MRU':'Minimum MRU'}<Input type="number" value={m.minimumAmountMru??''} onChange={e=>update(m.method,{minimumAmountMru:e.target.value?Number(e.target.value):null})}/></label><label className="text-sm">{lang==='ar'?'الحد الأقصى MRU':'Maximum MRU'}<Input type="number" value={m.maximumAmountMru??''} onChange={e=>update(m.method,{maximumAmountMru:e.target.value?Number(e.target.value):null})}/></label><label className="text-sm sm:col-span-2">التعليمات العربية<Textarea value={m.instructionsAr} onChange={e=>update(m.method,{instructionsAr:e.target.value})}/></label><label className="text-sm sm:col-span-2">Instructions françaises<Textarea value={m.instructionsFr} onChange={e=>update(m.method,{instructionsFr:e.target.value})}/></label></div><div className="mt-4 flex flex-wrap items-center gap-5"><label className="flex items-center gap-2 text-sm"><Checkbox checked={m.evidenceRequired} onCheckedChange={v=>update(m.method,{evidenceRequired:v===true})}/>{lang==='ar'?'الإثبات إلزامي':'Justificatif requis'}</label><label className="flex items-center gap-2 text-sm"><Checkbox checked={m.transactionReferenceRequired} onCheckedChange={v=>update(m.method,{transactionReferenceRequired:v===true})}/>{lang==='ar'?'المرجع إلزامي':'Référence requise'}</label><Button className={isRTL?'mr-auto':'ml-auto'} onClick={()=>save(m)} disabled={saving===m.method}>{lang==='ar'?'حفظ':'Enregistrer'}</Button></div></Card>)}</div></div></AdminLayout>
}
