import { useEffect, useMemo, useState } from 'react';
import { customFetch } from '@workspace/api-client-react';
import { AlertTriangle, CheckCircle2, Eye, RefreshCw, Search } from 'lucide-react';
import AdminLayout from '@/components/AdminLayout';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Checkbox } from '@/components/ui/checkbox';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { useAdminI18n } from '@/contexts/AdminI18nContext';
import { toast } from 'sonner';

type Review = { id:string; amountMru:number; clientReference:string; manualPaymentMethod:string; manualReviewStatus:string; submittedSenderName?:string|null; submittedSenderPhone?:string|null; submittedTransactionReference?:string|null; planName:string; evidencePreviewPath?:string|null; user?:{fullName?:string|null;email?:string|null}; riskIndicators?:{duplicateEvidence?:boolean;duplicateSubmittedReference?:boolean;expired?:boolean} };
type ListResponse = { success:true; data:Review[] };
const copy = {
  ar:{title:'مراجعات الدفع اليدوي',subtitle:'تحقق من وصول المال فعليًا قبل تفعيل أي اشتراك.',refresh:'تحديث',search:'ابحث بالاسم أو المرجع',user:'المستخدم',order:'الطلب',amount:'المبلغ',method:'الطريقة',status:'الحالة',review:'مراجعة',evidence:'إثبات الدفع الخاص',noEvidence:'لا يوجد إثبات مرفوع',risks:'مؤشرات المخاطر',duplicateEvidence:'صورة مستخدمة في طلب آخر',duplicateReference:'مرجع مقدم مكرر',expired:'الطلب منتهي',sender:'بيانات المرسل',verify:'تحقق وفعّل',more:'طلب معلومات إضافية',reject:'رفض',reason:'سبب الإجراء إلزامي',receivedAmount:'المبلغ المستلم فعليًا',transactionReference:'مرجع المعاملة الفعلي',recipientAccount:'حساب الاستلام',receivedAt:'تاريخ ووقت الاستلام',note:'ملاحظة التحقق الداخلية',confirm:'أؤكد أنني تحققت من محفظة/حساب التاجر وأن هذا الدفع وصل فعليًا.',close:'إغلاق'},
  fr:{title:'Vérifications manuelles',subtitle:'Confirmez la réception réelle des fonds avant toute activation.',refresh:'Actualiser',search:'Rechercher nom ou référence',user:'Utilisateur',order:'Commande',amount:'Montant',method:'Méthode',status:'Statut',review:'Examiner',evidence:'Justificatif privé',noEvidence:'Aucun justificatif',risks:'Indicateurs de risque',duplicateEvidence:'Image utilisée sur une autre demande',duplicateReference:'Référence déclarée en double',expired:'Commande expirée',sender:'Coordonnées expéditeur',verify:'Vérifier et activer',more:'Demander des informations',reject:'Rejeter',reason:'Motif obligatoire',receivedAmount:'Montant réellement reçu',transactionReference:'Référence réelle',recipientAccount:'Compte destinataire',receivedAt:'Date et heure de réception',note:'Note interne de vérification',confirm:'Je confirme avoir vérifié le portefeuille/compte marchand et que ce paiement a réellement été reçu.',close:'Fermer'},
};

export default function AdminManualPayments(){
 const {lang,isRTL}=useAdminI18n(); const c=copy[lang];
 const [rows,setRows]=useState<Review[]>([]); const [selected,setSelected]=useState<Review|null>(null); const [query,setQuery]=useState(''); const [loading,setLoading]=useState(true); const [previewUrl,setPreviewUrl]=useState<string|null>(null); const [reason,setReason]=useState('');
 const [form,setForm]=useState({receivedAmountMru:'',verifiedTransactionReference:'',recipientAccount:'',receivedAt:'',verificationNote:'',confirmReceived:false});
 const load=async()=>{setLoading(true);try{const r=await customFetch<ListResponse>('/api/admin/manual-payment-reviews',{responseType:'json'});setRows(r.data)}catch{toast.error(lang==='ar'?'تعذر تحميل المراجعات':'Chargement impossible')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 useEffect(()=>{if(!selected?.evidencePreviewPath){setPreviewUrl(null);return}let active=true,url:string|null=null;customFetch<Blob>(selected.evidencePreviewPath,{responseType:'blob'}).then(b=>{if(active){url=URL.createObjectURL(b);setPreviewUrl(url)}}).catch(()=>setPreviewUrl(null));return()=>{active=false;if(url)URL.revokeObjectURL(url)}},[selected?.id]);
 const filtered=useMemo(()=>rows.filter(r=>`${r.user?.fullName} ${r.user?.email} ${r.clientReference} ${r.submittedTransactionReference}`.toLowerCase().includes(query.toLowerCase())),[rows,query]);
 const act=async(action:'request-more-information'|'reject')=>{if(!selected||!reason.trim())return toast.error(c.reason);try{await customFetch(`/api/admin/manual-payment-reviews/${selected.id}/${action}`,{method:'POST',body:JSON.stringify({reason}),responseType:'json'});toast.success(lang==='ar'?'تم حفظ القرار':'Décision enregistrée');setSelected(null);setReason('');await load()}catch{toast.error(lang==='ar'?'تعذر حفظ القرار':'Échec de la décision')}};
 const verify=async()=>{if(!selected||!form.confirmReceived||!form.receivedAmountMru||!form.verifiedTransactionReference||!form.recipientAccount||!form.receivedAt||!form.verificationNote)return toast.error(lang==='ar'?'أكمل جميع حقول التحقق والتأكيد':'Complétez tous les champs');try{await customFetch(`/api/admin/manual-payment-reviews/${selected.id}/verify`,{method:'POST',body:JSON.stringify({...form,receivedAmountMru:Number(form.receivedAmountMru),receivedAt:new Date(form.receivedAt).toISOString(),paymentMethod:selected.manualPaymentMethod,verificationSource:'merchant_wallet_statement'}),responseType:'json'});toast.success(lang==='ar'?'تم التحقق والتفعيل ذريًا':'Paiement vérifié et abonnement activé');setSelected(null);await load()}catch{toast.error(lang==='ar'?'فشل التحقق ولم يُفعّل الاشتراك':"Échec: l’abonnement n’a pas été activé")}};
 return <AdminLayout><div className="mx-auto max-w-7xl space-y-6 p-6" dir={isRTL?'rtl':'ltr'}>
  <div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-bold text-foreground">{c.title}</h1><p className="mt-1 text-sm text-muted-foreground">{c.subtitle}</p></div><Button variant="outline" onClick={load} disabled={loading}><RefreshCw className="h-4 w-4"/>{c.refresh}</Button></div>
  <div className="relative max-w-md"><Search className={`absolute top-2.5 h-4 w-4 text-muted-foreground ${isRTL?'right-3':'left-3'}`}/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder={c.search} className={isRTL?'pr-9':'pl-9'}/></div>
  <Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-muted"><tr>{[c.user,c.order,c.amount,c.method,c.status,''].map((h,i)=><th key={i} className="px-4 py-3 text-start font-medium">{h}</th>)}</tr></thead><tbody className="divide-y divide-border">{filtered.map(r=><tr key={r.id} className="hover:bg-muted/50"><td className="px-4 py-3"><b>{r.user?.fullName||'—'}</b><div className="text-xs text-muted-foreground">{r.user?.email}</div></td><td className="px-4 py-3 font-mono text-xs">{r.clientReference}</td><td className="px-4 py-3 tabular-nums">{r.amountMru} MRU</td><td className="px-4 py-3">{r.manualPaymentMethod}</td><td className="px-4 py-3"><span className="rounded-full bg-primary/10 px-2.5 py-1 text-xs font-medium text-primary">{r.manualReviewStatus}</span></td><td className="px-4 py-3"><Button size="sm" variant="outline" onClick={()=>{setSelected(r);setForm(f=>({...f,receivedAmountMru:String(r.amountMru)}))}}><Eye className="h-4 w-4"/>{c.review}</Button></td></tr>)}</tbody></table>{!loading&&!filtered.length?<div className="p-10 text-center text-sm text-muted-foreground">{lang==='ar'?'لا توجد مراجعات مطابقة':'Aucune vérification'}</div>:null}</div></Card>
  {selected?<div className="fixed inset-0 z-50 flex justify-end bg-black/45" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><section className="h-full w-full max-w-2xl overflow-y-auto bg-background p-6 shadow-lg"><div className="mb-6 flex items-start justify-between"><div><h2 className="text-xl font-semibold">{selected.clientReference}</h2><p className="text-sm text-muted-foreground">{selected.user?.fullName} · {selected.amountMru} MRU</p></div><Button variant="outline" onClick={()=>setSelected(null)}>{c.close}</Button></div><div className="space-y-6">
   <section><h3 className="mb-2 font-semibold">{c.evidence}</h3>{previewUrl?<img src={previewUrl} alt={c.evidence} className="max-h-96 w-full rounded-xl border border-border object-contain"/>:<div className="rounded-xl bg-muted p-8 text-center text-sm text-muted-foreground">{c.noEvidence}</div>}</section>
   <section className="grid gap-3 sm:grid-cols-2"><div><small className="text-muted-foreground">{c.sender}</small><div>{selected.submittedSenderName||'—'} · {selected.submittedSenderPhone||'—'}</div></div><div><small className="text-muted-foreground">{c.transactionReference}</small><div className="font-mono">{selected.submittedTransactionReference||'—'}</div></div></section>
   {(selected.riskIndicators?.duplicateEvidence||selected.riskIndicators?.duplicateSubmittedReference||selected.riskIndicators?.expired)?<section className="rounded-xl bg-destructive/10 p-4 text-destructive"><h3 className="mb-2 flex items-center gap-2 font-semibold"><AlertTriangle className="h-4 w-4"/>{c.risks}</h3><ul className="list-inside list-disc text-sm">{selected.riskIndicators.duplicateEvidence?<li>{c.duplicateEvidence}</li>:null}{selected.riskIndicators.duplicateSubmittedReference?<li>{c.duplicateReference}</li>:null}{selected.riskIndicators.expired?<li>{c.expired}</li>:null}</ul></section>:null}
   <section className="space-y-3 border-t border-border pt-5"><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">{c.receivedAmount}<Input type="number" value={form.receivedAmountMru} onChange={e=>setForm({...form,receivedAmountMru:e.target.value})}/></label><label className="text-sm">{c.transactionReference}<Input value={form.verifiedTransactionReference} onChange={e=>setForm({...form,verifiedTransactionReference:e.target.value})}/></label><label className="text-sm">{c.recipientAccount}<Input value={form.recipientAccount} onChange={e=>setForm({...form,recipientAccount:e.target.value})}/></label><label className="text-sm">{c.receivedAt}<Input type="datetime-local" value={form.receivedAt} onChange={e=>setForm({...form,receivedAt:e.target.value})}/></label></div><label className="text-sm">{c.note}<Textarea value={form.verificationNote} onChange={e=>setForm({...form,verificationNote:e.target.value})}/></label><label className="flex items-start gap-3 rounded-xl bg-muted p-3 text-sm"><Checkbox checked={form.confirmReceived} onCheckedChange={v=>setForm({...form,confirmReceived:v===true})}/><span>{c.confirm}</span></label><Button onClick={verify} disabled={!form.confirmReceived}><CheckCircle2 className="h-4 w-4"/>{c.verify}</Button></section>
   <section className="space-y-3 border-t border-border pt-5"><Textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder={c.reason}/><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>act('request-more-information')}>{c.more}</Button><Button variant="destructive" onClick={()=>act('reject')}>{c.reject}</Button></div></section>
  </div></section></div>:null}
 </div></AdminLayout>
}
